### ISSUE TITLE
Can't go from `scalaz.Monad[F]` to `cats.Applicative[F]`

### ISSUE THREAD

**Issue by edmundnoble** [djspiewak/shims#18] opened 2018-04-04 23:07 UTC
As you might expect, chaining implicits and subtyping doesn't work.

**Comment by djspiewak** [comment] 2018-04-29 21:59
Actually this absolutely *should* work, mostly because it would be going from the `scalaz.Applicative[F]` to `cats.Applicative[F]`. I've tested this in the past with `Equal` (materializing via `Order`).

**Comment by djspiewak** [comment] 2018-04-30 15:52
```
[info] Starting scala interpreter...
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> import cats._
import cats._

scala> import scalaz._
import scalaz._

scala> sealed trait Foo[A]
defined trait Foo

scala>     implicit val mon: scalaz.Monad[Foo] = null
mon: scalaz.Monad[Foo] = null

scala> import shims._
import shims._

scala>     cats.Applicative[Foo]
res2: cats.Applicative[Foo] = shims.conversions.ApplicativeConversions$$anon$5@7e0d31ae
```

Closing this for now. Is there something missing from my reproduction?

**Closed by djspiewak** 2018-04-30 15:52 UTC
Labels: bug
